global:
  scrape_interval: 5s

scrape_configs:
  # Scrape Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  # Scrape your sample Flask app
  - job_name: 'sample-app'
    metrics_path: /metrics   # Make sure your Flask app exposes /metrics
    static_configs:
      - targets: ['sample-app:8085']

  # Scrape Node Exporter (system metrics)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
